# Default values for demo-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: ghcr.io/farazmateen/tb-do-image
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: [dockerconfigjson-github-com]

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "200m"

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  # targetMemoryUtilizationPercentage: 80

env:
  ENVIRONMENT: PROD
  HOST: localhost
  PORT: '8000'
  REDIS_HOST: redis-service.redis.svc.cluster.local
  REDIS_PORT: '6379'
  REDIS_DB: '0'

nodeSelector: {}

tolerations: []

affinity: {}

topologySpreadConstraints:
  enabled: true

probes:
  readiness:
    httpGet:
      path: /
      port: 8000
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    httpGet:
      path: /
      port: 8000
    initialDelaySeconds: 5
    periodSeconds: 10
