#apiVersion: v1
#kind: Secret
#metadata:
#  name: redis-password
#  namespace: redis
#type: Opaque
#data:
#  password: cGFzc3dvcmQ= # Base64-encoded "password". Replace with your own encoded value.
#---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode no
    #    requirepass password
    appendonly yes
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2
        ports:
        - containerPort: 6379
          #        env:
          #        - name: REDIS_PASSWORD
          #          valueFrom:
          #            secretKeyRef:
          #              name: redis-password
          #              key: password
        volumeMounts:
        - name: redis-config-volume
          mountPath: /usr/local/etc/redis/redis.conf
          subPath: redis.conf
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
          #        envFrom:
          #        - secretRef:
          #            name: redis-password
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      volumes:
        - name: redis-config-volume
          configMap:
            name: redis-config
---
apiVersion: v1
kind: Pod
metadata:
  name: redis-client
  namespace: redis
spec:
  containers:
  - name: redis-client
    image: redis:6.2
    command: ["sh", "-c", "exec sleep infinity"]



